# Generated by Django 3.0.3 on 2020-05-02 14:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserver_id', models.CharField(max_length=200)),
                ('people', models.CharField(choices=[('1', 'one person'), ('2', 'two people'), ('3', 'three people'), ('4', 'four people'), ('5', 'five  people')], default='1', max_length=5)),
                ('date_reserved', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('name', models.CharField(choices=[('cards games', 'cards games'), ('billar', 'billar'), ('chess', 'chess'), ('poker table', 'poker table')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('transaction_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.CharField(max_length=200)),
            ],
        ),
    ]
