# Generated by Django 3.0.5 on 2020-05-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='Number',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
