# Generated by Django 3.0.5 on 2020-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_gadget_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='Number',
            field=models.IntegerField(default=10),
        ),
    ]
