# Generated by Django 3.0.5 on 2020-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_auto_20200505_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.CharField(default='img.png', max_length=100),
        ),
    ]
