# Generated by Django 3.1.2 on 2020-10-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_events_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('employer', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='accountType',
            field=models.CharField(blank=True, default='User', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Booking.opportunities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.guest')),
            ],
        ),
    ]
